/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package B8;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author dungn
 */
public class Caculator extends javax.swing.JFrame {

    /**
     * Creates new form Caculator
     */
    public Caculator() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSothu1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSothu2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKetqua = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 36)); // NOI18N
        jLabel1.setText("Máy tính đơn giản");

        jLabel2.setText("Số thứ nhất");

        jLabel3.setText("Số thứ hai");

        jLabel4.setText("Kết quả");

        txtKetqua.setEditable(false);

        btnCong.setText("Cộng");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnTru.setText("Trừ");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        btnNhan.setText("Nhân");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });

        btnChia.setText("Chia");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCong)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSothu1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSothu2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTru)
                                .addGap(46, 46, 46)
                                .addComponent(btnNhan)
                                .addGap(46, 46, 46)
                                .addComponent(btnChia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSothu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSothu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(btnNhan)
                    .addComponent(btnChia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        // B1. Lấy số thứ nhất từ người dùng nhập vào 
        if(txtSothu1.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Moi nhap so thu nhat");
            return;
        }
        BigDecimal soThuNhat;
        try{
             double stn = Double.parseDouble(txtSothu1.getText());
             soThuNhat = BigDecimal.valueOf(stn);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
                    "Dinh dang so thu nhat khong hop le. Moi nhap lai");
            return;// Khoong thuc hien doan code phia sau
        }
       
        // B2. Lấy số thứ hai từ người dùng nhập vào
         if(txtSothu2.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Moi nhap so thu nhat");
            return;
        }
         BigDecimal soThuHai ;
        try{
             double sth = Double.parseDouble(txtSothu2.getText());
             soThuHai = BigDecimal.valueOf(sth);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
                    "Dinh dang so thu nhat khong hop le. Moi nhap lai");
            return;
        }
        //B3. Cộng hai số
        BigDecimal ketQua = soThuNhat.add(soThuHai) ;
        //B4. Hiển thị kết quả ở ô kết quá
        txtKetqua.setText(ketQua + "");
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        // Bước 1: Lấy số thứ nhất từ người dùng nhập vào
            if (txtSothu1.getText().isBlank()) {
           JOptionPane.showMessageDialog(this, "Mời nhập số thứ nhất");
           return;
           }
            BigDecimal soThuNhat;
            try {
                double stn = Double.parseDouble(txtSothu1.getText());
                soThuNhat = BigDecimal.valueOf(stn);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ nhất không hợp lệ. Mời nhập lại");
                return;
            }
        // Bước 2: Lấy số thứ hai từ người dùng nhập vào
            if (txtSothu2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số thứ hai");
            return;
            }
            BigDecimal soThuHai;
            try {
                double sth = Double.parseDouble(txtSothu2.getText());
                soThuHai = BigDecimal.valueOf(sth);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ hai không hợp lệ. Mời nhập lại");
                return;
            }
        // Bước 3: Thực hiện phép trừ
            BigDecimal ketQua = soThuNhat.subtract(soThuHai);
         // Bước 4: Hiển thị kết quả ở ô kết quả
            txtKetqua.setText(ketQua.toString());
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        // TODO add your handling code here:
        // Bước 1: Lấy số thứ nhất từ người dùng nhập vào
             if (txtSothu1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số thứ nhất");
            return;         
            }
             BigDecimal soThuNhat;
            try {
                double stn = Double.parseDouble(txtSothu1.getText());
                soThuNhat = BigDecimal.valueOf(stn);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ nhất không hợp lệ. Mời nhập lại");
                return;
            }
        // Bước 2: Lấy số thứ hai từ người dùng nhập vào
            if (txtSothu2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số thứ hai");
            return;
            }
            BigDecimal soThuHai;
            try {
                double sth = Double.parseDouble(txtSothu2.getText());
                soThuHai = BigDecimal.valueOf(sth);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ hai không hợp lệ. Mời nhập lại");
                return;
            }
        // Bước 3: Thực hiện phép nhân
            BigDecimal ketQua = soThuNhat.multiply(soThuHai);
        // Bước 4: Hiển thị kết quả ở ô kết quả
            txtKetqua.setText(ketQua.toString());
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
        // Bước 1: Lấy số thứ nhất từ người dùng nhập vào
             if (txtSothu1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số thứ nhất");
            return;         
            }
             BigDecimal soThuNhat;
            try {
                double stn = Double.parseDouble(txtSothu1.getText());
                soThuNhat = BigDecimal.valueOf(stn);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ nhất không hợp lệ. Mời nhập lại");
                return;
            }
        // Bước 2: Lấy số thứ hai từ người dùng nhập vào
            if (txtSothu2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời nhập số thứ hai");
            return;
            }
            BigDecimal soThuHai;
            try {
                double sth = Double.parseDouble(txtSothu2.getText());
                soThuHai = BigDecimal.valueOf(sth);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Định dạng số thứ hai không hợp lệ. Mời nhập lại");
                return;
            }
        //Bước 3: Kiểm tra phép chia cho 0
            if (soThuHai.compareTo(BigDecimal.ZERO) == 0) {
                JOptionPane.showMessageDialog(this, "Không thể chia cho 0. Mời nhập số thứ hai khác 0");
                return;
            }

        // Bước 4:  Thực hiện phép chia
            BigDecimal ketQua = soThuNhat.divide(soThuHai, 2, BigDecimal.ROUND_HALF_UP);

        // Bài 5; Hiển thị kết quả ở ô kết quả
            txtKetqua.setText(ketQua.toString());   
        
    }//GEN-LAST:event_btnChiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtKetqua;
    private javax.swing.JTextField txtSothu1;
    private javax.swing.JTextField txtSothu2;
    // End of variables declaration//GEN-END:variables
}
